server:
  port: 8761
spring:
  security:
    basic:
      enabled: true
    user:
      name: t4edu
      password: t4edu2021
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
